# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build all formats
formats: all

python:
  # Install our python package before building the docs
  install:
    - requirements: docs/source/requirements.txt
    - method: pip
      path: .
      
 # Set the version of Python and other tools you might need
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"


# Build documentation in the docs/source/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false
  
  
